MrNeRF/LichtFeld-Studio

src/read_utils.cu

Of course I have existing (nerf) datasets whose camera model isn't supported, but needed to know what that model actually is (OPENCV). So I added a switch() for that. There might be clever ways in C++XX to do it nicer, but this works.

Show info on unsupported camera model

---

README.md
src/gaussian.cu
src/main.cu

Okay, seems I mistimed trying to add a status line with your addition of the convergence threshold :)
This adds a status line that is continuously refreshed with basic stats, including avg iterations/s and overall time. I commented out the periodic pruning and opacity-clearing messages as they were causing the status line to get newlined and start over.
If you don't want to use this then don't.
PS I need to start using feature branches on my end...

Status line

---

cuda_rasterizer/rasterizer_impl.h

I needed to include `<cstdint>` to avoid
```
/home/miriam/gaussian-splatting-cuda/cuda_rasterizer/rasterizer_impl.h(22): error: namespace "std" has no member "uintptr_t"
std::size_t offset = (reinterpret_cast<std::uintptr_t>(chunk) + alignment - 1) & ~(alignment - 1);
^
/home/miriam/gaussian-splatting-cuda/cuda_rasterizer/rasterizer_impl.h(37): error: identifier "uint32_t" is undefined
uint32_t* point_offsets;
^
/home/miriam/gaussian-splatting-cuda/cuda_rasterizer/rasterizer_impl.h(38): error: identifier "uint32_t" is undefined
uint32_t* tiles_touched;
^
/home/miriam/gaussian-splatting-cuda/cuda_rasterizer/rasterizer_impl.h(45): error: identifier "uint32_t" is undefined
uint32_t* n_contrib;
^
/home/miriam/gaussian-splatting-cuda/cuda_rasterizer/rasterizer_impl.h(53): error: identifier …
```

include cstdint in rasterizer_impl.h

---

CMakeLists.txt

As described in https://cmake.org/cmake/help/latest/command/find_package.html, `<PackageName>_DIR` can be used for `find_package()`, the motivation of switching from `CMAKE_PREFIX_PATH` to `<PackageName>_DIR` for libtorch is because ideally `CMAKE_PREFIX_PATH` should be reserved for a central package manager, e.g. vcpkg, for finding other dependencies specified in `find_package()`, e.g. TBB (not by default available on Windows, can be built by vcpkg).

use Torch_DIR to find libtorch instead of CMAKE_PREFIX_PATH

---

src/camera_utils.cu
src/read_utils.cu

Couldn't figure out why the `transpose()` was there at the first place, in my opinion this causes confusion and should be removed. After fixing up `getWorld2View2` and `getWorld2View2Eigen` I can confirm that the truck dataset works like usual.

remove transpose() on camera_info->_R that causes confusion for reading

---

src/main.cu

`std::reverse` in `get_random_indices` looks like unnecessary computation to me, so proposing to remove it, also truck dataset still works like usual after this change

remove unnecessary std::reverse

---

src/gaussian.cu

slicing seems unnecessary when mask is size [N, 1]

remove unnecessary slicing when calculating indices

---

src/gaussian.cu

`selected_pts_mask` in `densify_and_split` is [N] instead of [N, 1] like in `densify_and_clone`, so the `.squeeze(-1)` here should be redundant

remove unnecessary .squeeze when calculating indices

---

src/gaussian.cu

selected_pts_mask is [N], so the .squeeze(-1) here should be redundant

remove unnecessary .squeeze when calculating prune_filter

---

CMakeLists.txt

Fixes
```
/home/miriam/gaussian-splatting-cuda/include/kernels/backward.h:19:10: fatal error: glm/glm.hpp: No such file or directory
19 | #include <glm/glm.hpp>
|          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/gaussian_kernels.dir/build.make:125: CMakeFiles/gaussian_kernels.dir/kernels/cuda_rasterizer/backward.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/miriam/gaussian-splatting-cuda/kernels/cuda_rasterizer/forward.cu:13:
/home/miriam/gaussian-splatting-cuda/include/kernels/forward.h:19:10: fatal error: glm/glm.hpp: No such file or directory
19 | #include <glm/glm.hpp>
|          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/gaussian_kernels.dir/build.make:110: …
```

fix fatal error: glm/glm.hpp: No such file or directory

---

gsplat/CMakeLists.txt

Seeing the below without this PR
```
/home/miriam/gaussian-splatting-cuda/gsplat/Common.h:5:10: fatal error: glm/gtc/type_ptr.hpp: No such file or directory
5 | #include <glm/gtc/type_ptr.hpp>
|          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

fix compilation error due to glm

---

src/trainer.cpp

Now if `-i 1000`, it will save splat_1001.ply, this change makes it save splat_1000.ply, which I think should be better align with what the user expect it to behave

save splat_iterations.ply instead of splat_iterations+1.ply

---

src/rasterizer_autograd.cpp

My understanding is grad_outputs should already be in CUDA and contiguous so these should be redundant and can be removed for better readability. Ran the truck dataset and it seems to run fine.

grad_outputs should already be in CUDA and contiguous

---

include/core/trainer.hpp
src/trainer.cpp

Closes #147 
The memory-usage reduction was measured by polling `nvidia-smi` at one-second intervals using a shell script. 
<details>
<summary>
<code>monitor.sh</code> 
</summary>
<p>
```bash
#!/bin/bash
#
set -euo pipefail
if [ "${#}" -lt 3 ]; then
printf 'Usage: %s INTERVAL_SEC OUTPUT_FILE -- COMMAND [ARGS...]\n' "$(basename "${0}")" >&2
exit 1
fi
readonly interval="${1}"
readonly outfile="${2}"
shift 2
if [ "${1}" = "--" ]; then
shift
fi
readonly cmd=( "${@}" )
for tool in nvidia-smi date awk grep; do
if ! command -v "${tool}" >/dev/null 2>&1; then
printf 'Error: %s not found in PATH\n' "${tool}" >&2
exit 1
fi
done
if [ ! -e "${outfile}" ]; then
printf 'timestamp,memory_MiB\n' > "${outfile}"
fi
"${cmd[@]}" &
readonly pid=$!
printf 'Started process PID=%s: %s\n' "${pid}" "${cmd[*]}" …
```

Reduce GPU usage by calling backward per loss

---

src/metrics.cpp

Corrects the bug in `metrics.cpp` which uses asymm 1D gaussian kernel for computing ssim
The affect on metric is negligible
SSIM with asymmetric 1D gaussian kernel SSIM: 0.85838
SSIM with symmetric 1D gaussian kernel SSIM: 0.85798

Fix: corrects 1D gaussian kernel in metrics

---

include/visualizer/viewport.hpp
src/viewer.cpp

inserted rotation around center (middle mouse+drag) and roll rotation ('r' + wheel)
I find the current navigation quite difficult. 
I added a new ability to rotate the camera around the center of the model (mouse 3 + grag) 
this is inspired from instant-ngp , 
after this rotation you might want to fix the camera roll , so i added 'R' + scroll  to rotating around the roll axis.
hope you will find that helping ( it certainly helped me :) ).

camera view modification

---

include/visualizer/detail.hpp
src/viewer.cpp

added shortcut menu  to the main window . for now the shortcuts are:
1. mouse right + drag = local translate the camera
2. mouse left + drag = local rotate the camera in the pitch yaw directions
3. mouse middle + drag = rotate the camera around the scene center
4. scroll = zoom
5. R+scroll = rotate the camera around the roll axis

added shortcuts menu

---

CMakeLists.txt

in windows the vcpkg_root path needs to be converted to cmake path

convert VCPKG_ROOT to platform independent cmake path

---

src/visualizer/gui/gui_manager.cpp
src/visualizer/gui/gui_manager.hpp
src/visualizer/input/camera_controller.cpp
src/visualizer/input/camera_controller.hpp
src/visualizer/input/input_handler.cpp
src/visualizer/input/input_handler.hpp
src/visualizer/input/input_manager.cpp
src/visualizer/input/input_manager.hpp
src/visualizer/input/input_priority.hpp
src/visualizer/tools/crop_box_tool.cpp
src/visualizer/tools/crop_box_tool.hpp
src/visualizer/tools/tool_base.hpp
src/visualizer/tools/tool_manager.cpp

Priority-based input handling system that solves the issue where mouse interactions were affecting both the UI and the 3D scene simultaneously. 
The system now processes input events in order of priority: GUI widgets get first chance to consume events, followed by tools like the crop box, and finally the camera controls.
Fixes https://github.com/MrNeRF/gaussian-splatting-cuda/issues/221!

Priority-based input handling 

---

src/visualizer/rendering/renderer.hpp

Fix for std pointer types if running cmake with -DENABLE_CUDA_GL_INTEROP=OFF They are probably included indirectly otherwise.
For me I were already disabling the interop earlier in the cmake file manually since I had issues with it on WSL (windows + Ubuntu 24).
This flag from earlier PR makes it easier but made it fail to compile.
This fixes it for me, hope it helps others too.

fix compile error if using ENABLE_CUDA_GL_INTEROP=OFF

---

include/core/events.hpp
include/core/training_progress.hpp
src/visualizer/gui/gui_manager.cpp
src/visualizer/input/camera_controller.cpp
src/visualizer/input/camera_controller.hpp
src/visualizer/input/input_handler.cpp
src/visualizer/input/input_manager.cpp
src/visualizer/window/window_manager.cpp

- Fixes: Camera didn't work sometimes.
- Fixes: Camera movement break after dragging Window, resizing, or switching the app.
This should be more robust!

bugfix camera controls

---

vcpkg.json

based on the suggestion here: https://github.com/MrNeRF/gaussian-splatting-cuda/pull/317#issuecomment-3208154710

save vcpkg.json as UTF-8 instead of UTF-8-BOM

---

.github/workflows/ubuntu.yml

doesn't seem possible to overwrite the ccache when it's in use, try using rolling cache this time and see if it works

restore-keys with rolling cache for ccache in github actions

---

src/visualizer/gui/panels/world_transform_panel.cpp

brought back +/- arrow for world transform. 
the current mechanism was drag input and it was not good since the the input bar were too short

World transform +/-  

---

.gitignore
CMakeLists.txt
README.md

Hello it is me ~mario~ maybe you didn't forget about our convo from like yesterday (?), so yeah I would like to fix the https://github.com/MrNeRF/gaussian-splatting-cuda/issues/357
But for now I don't like the approach for hardcoding vcpkg using env variables, so it is really better to clone vcpkg to the root folder of repo project.
So it is really nice to specify cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="./vcpkg/scripts/buildsystems/vcpkg.cmake" because we could possibly have a case when user nuked its vcpkg and a scenario IT was used for different projects (not just for gaussian splatting cuda) and since it was ruined he can't just easily resolve the dependencies (or remember them well) that were used and handled by single vcpkg instance that was specified and …

vcpkg hardcode approach alternative

---

.gitignore
CMakeLists.txt

tested and generated on three scenarios: 
> cmake -B build -DCMAKE_TOOLCHAIN_FILE="./vcpkg/scripts/buildsystems/vcpkg.cmake"
> cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="./vcpkg/scripts/buildsystems/vcpkg.cmake"
> cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE="./vcpkg/scripts/buildsystems/vcpkg.cmake"
If there's some mistake on user's side we will raise message(FATAL_ERROR and show user where the problem is. Currently I did checking on existance of root folders for debug and release and for libtorch on both sides of build types.

improving CMake on Windows;

---

.github/workflows/ubuntu.yml
CMakeLists.txt
README.md
docs/docs/installation/building/windows.md
fastgs/CMakeLists.txt
gsplat/CMakeLists.txt
src/loader/CMakeLists.txt
src/visualizer/CMakeLists.txt

Suddenly I have to use clang-cl now, but it treats -Wall as -Weverything so clang-cl users have a lot of "not compatible with c++98" warnings
CXX_COMPILER_FRONTEND_VARIANT was added in version 3.30, which allows to separate clang-cl (MSVC frontend)
and clang (GNU frontend) to use different flags.
The other compilers (MSVC, GNU) can only have one frontend, so their flags remain unchanged.

cmake: bump 3.30 and use CXX_COMPILER_FRONTEND_VARIANT

---

src/training/trainer.cpp
src/visualizer/gui/panels/training_panel.cpp

This change adds 2 checkboxes to to GUI:
* under dataset, we add "import from Reality Capture"
* under optimization, we add "GUT"
These checkboxes can be used to enable training of distorted images through the GUI without the need to specify their startup parameters.
We also change the error message that is displayed when training with distorted images is detected.
Finally, we allow a "reset" of the dataset in case a training error occurs. This allows the user to restart training with adjusted parameters without having to close the application.

Expose --gut (GUT) and --rc (Reality Capture) in GUI

---

src/core/camera.cpp
src/loader/formats/colmap.cpp
src/loader/formats/transforms.cpp

1. fixed some memory leak bugs related to not freeing image after load_image
2. switch load_image with get_image_info when load_image was called only for the image size

fix memory leak bugs and get_image_info usage

---

include/core/events.hpp
src/visualizer/gui/panels/main_panel.cpp
src/visualizer/input/input_controller.cpp
src/visualizer/input/input_controller.hpp
src/visualizer/internal/viewport.hpp
src/visualizer/rendering/rendering_manager.hpp

- A checkbox to set a gimbal lock
- Inverted rotation axes
How to test:
Right-click drag to rotate the camera. When moving the mouse in circles on the screen this usually leads to a tilted horizon.
With the "Lock Gimbal" checkbox enabled, the horizon should stay leveled.
When starting a rotation with a tilted horizon but the checkbox checked, the camera will correct its up-direction in the first frame.

Changes to camera rotation

---

src/visualizer/gui/gui_manager.cpp
src/visualizer/gui/panels/training_panel.cpp

With extending the functionality of LFS, the current "rendering settinsg" tab was getting crowded with a lot of settings, buttons, checkboxes, ...
This PR implements a "training tab", where we move the training controls.
When the user adds a dataset, this tab becomes automatically visible.
When the user clears the dataset, this tab will be hidden.
We make the left panel slightyly bigger to fit the 2 tabs.
We also move 2 (important) training paramaters to a move visible location
* max gaussians
* iterations
Before:
After:

Traing tab for training settings

---

src/visualizer/gui/panels/training_panel.cpp

This PR exposes the settings --bilateral-grid in GUI
We also move the GUT checkbox to the "features" tab.
Before:
After:

Expose --bilateral-grid  in GUI

---

src/visualizer/gui/gui_manager.cpp

This change will detect the OS dpi scaling and adjust the font used for displaying accordingly.
Also tried this, but the quality of the font was not very good when upscaling using this method
````
// Scale fonts according to monitor DPI -> causes issues with pixel-perfect rendering
// we will scale the font size instead
// ImGui::GetIO().FontGlobalScale = xscale; 
// ImGui::GetStyle().ScaleAllSizes(2.0f);
````

DPI Scaling for GUI Font loading
