- README.md
Appreciate all the work on this faster implementation! The ReadMe was very clear -- only issue I hit was an undocumented dependency on TBB, which I've added here.
> [ReadMe] add tbb to software dependencies

- README.md
Added an Version for Ubuntu 20.04 , NVIDIA RTX 3050
> added NVIDIA RTX 3050

- includes/gaussian.cuh
- src/gaussian.cu
- src/main.cu
What is the original intention of this arg? Doesn't seem to be used in any commented out code either. Let's remove for better readability?
> remove unused max_screen_size

- include/core/splat_data.hpp
- src/splat_data.cpp
Should be fixed: https://github.com/MrNeRF/gaussian-splatting-cuda/issues/106
> Fix async file save corruption

- include/core/parameters.hpp
- include/core/rasterizer.hpp
- include/core/rasterizer_autograd.hpp
- include/core/trainer.hpp
- parameter/optimization_params.json
- src/argument_parser.cpp
- src/parameters.cpp
- src/rasterizer.cpp
- src/rasterizer_autograd.cpp
- src/splat_data.cpp
- src/trainer.cpp
Support different render modes RGB, RGB_D, ED, D, and RGB_ED.
> add gsplat supported rendermodes

- CMakeLists.txt
- include/core/mcmc.hpp
- include/core/parameters.hpp
- include/core/selective_adam.hpp
- parameter/optimization_params.json
- src/argument_parser.cpp
- src/mcmc.cpp
- src/parameters.cpp
- src/selective_adam.cpp
Shaves off at least one-third of the training time. Though the metrics are thrown under the bus :bus:  😅
> Selective adam implementation

- include/core/trainer.hpp
- include/visualizer/detail.hpp
- src/main.cpp
- src/trainer.cpp
- src/viewer.cpp
Closes https://github.com/MrNeRF/gaussian-splatting-cuda/issues/125
> Issue 125/trainer architecture

- include/core/parameters.hpp
- include/visualizer/detail.hpp
- scripts/benchmark_mipnerf360.sh
- src/argument_parser.cpp
- src/parameters.cpp
- src/trainer.cpp
- src/viewer.cpp
> activate antialiasing

- include/core/dataset_reader.hpp
- include/core/transforms_reader.hpp
- src/dataset_reader.cpp
In case of failure to load I want to add more information to the user (including Colmap directory structures)
> added more verbosity to data set reader

- CMakeLists.txt
- include/visualizer/detail.hpp
- include/visualizer/gui_manager.hpp
- include/visualizer/viewer_notifier.hpp
- src/gui_manager.cpp
- src/viewer.cpp
viewer.cpp is growing too big!
> refactor viewer.cpp/detail.hpp

- src/visualizer/gui/gui_manager.cpp
- src/visualizer/gui/panels/main_panel.cpp
- src/visualizer/gui/panels/scene_panel.cpp
- src/visualizer/gui/windows/camera_controls.cpp
- src/visualizer/gui/windows/file_browser.cpp
- src/visualizer/gui/windows/scripting_console.cpp
> Dock panels enabled

- parameter/optimization_params.json
> Remove the duplicated `skip_intermediate` key

- include/core/mcmc.hpp
- parameter/default_optimization_params.json
- parameter/mcmc_optimization_params.json
- src/argument_parser.cpp
- src/default_strategy.cpp
- src/mcmc.cpp
- src/parameters.cpp
- src/strategy.cpp
- src/visualizer/tools/world_transform_tool.cpp
* Remove selective Adam parameter
* cleanup mcmc
> clean up mcmc

- include/core/camera.hpp
- include/core/dataset.hpp
- include/core/parameters.hpp
- include/core/trainer.hpp
- parameter/default_optimization_params.json
- parameter/mcmc_optimization_params.json
- scripts/benchmark_mipnerf360.sh
- scripts/timing_mipnerf360.sh
- src/argument_parser.cpp
- src/camera.cpp
- src/parameters.cpp
- src/trainer.cpp
Improvements from https://github.com/MrNeRF/gaussian-splatting-cuda/pull/244
> infinite datasampler and cuda streams

- include/core/events.hpp
- src/visualizer/CMakeLists.txt
- src/visualizer/gui/panels/main_panel.cpp
- src/visualizer/gui/panels/tools_panel.cpp
- src/visualizer/input/input_manager.cpp
- src/visualizer/rendering/rendering_manager.cpp
- src/visualizer/rendering/rendering_manager.hpp
- src/visualizer/rendering/rendering_pipeline.cpp
- src/visualizer/rendering/rendering_pipeline.hpp
- src/visualizer/tools/background_tool.cpp
- src/visualizer/tools/background_tool.hpp
- src/visualizer/tools/tool_manager.cpp
- src/visualizer/visualizer_impl.cpp
Add background color tool to viewer. 
Important: No impact on training, alter simply the background color in the viewer!
> background color tool

- include/core/events.hpp
- include/core/rasterizer.hpp
- include/visualizer/visualizer.hpp
- src/application.cpp
- src/visualizer/CMakeLists.txt
- src/visualizer/gui/panels/main_panel.cpp
- src/visualizer/rendering/point_cloud_renderer.cpp
- src/visualizer/rendering/point_cloud_renderer.hpp
- src/visualizer/rendering/rendering_manager.cpp
- src/visualizer/rendering/rendering_manager.hpp
- src/visualizer/rendering/rendering_pipeline.cpp
- src/visualizer/rendering/rendering_pipeline.hpp
- src/visualizer/resources/shaders/point_cloud.frag
- src/visualizer/resources/shaders/point_cloud.vert
- src/visualizer/visualizer_impl.hpp
https://github.com/user-attachments/assets/10377d1b-a68d-4b12-861b-73be4cc0864a
> Point cloud rendering

- .github/workflows/ubuntu.yml
fixes https://github.com/MrNeRF/gaussian-splatting-cuda/issues/323
> cache libtorch in github actions

- .github/workflows/ubuntu.yml
lots of gotchas in github actions
> fix invalid ccache path for github actions

- include/core/events.hpp
- include/core/splat_data.hpp
- include/rendering/rendering.hpp
- src/rendering/CMakeLists.txt
- src/rendering/point_cloud_renderer.hpp
- src/rendering/rendering_engine_impl.cpp
- src/rendering/rendering_engine_impl.hpp
- src/rendering/rendering_pipeline.cpp
- src/rendering/rendering_pipeline.hpp
- src/rendering/resources/shaders/translation_gizmo.frag
- src/rendering/resources/shaders/translation_gizmo.vert
- src/rendering/translation_gizmo.cpp
- src/rendering/translation_gizmo.hpp
- src/splat_data.cpp
- src/visualizer/CMakeLists.txt
- src/visualizer/gui/panels/world_transform_panel.cpp
- src/visualizer/input/input_controller.cpp
- src/visualizer/input/input_controller.hpp
- src/visualizer/rendering/rendering_manager.cpp
- src/visualizer/rendering/rendering_manager.hpp
- src/visualizer/tools/tool_base.hpp
- src/visualizer/tools/tools_panel.cpp
- src/visualizer/tools/translation_gizmo_tool.cpp
- src/visualizer/tools/translation_gizmo_tool.hpp
- src/visualizer/visualizer_impl.cpp
- src/visualizer/visualizer_impl.hpp
> Translation gizmo

- .github/workflows/clang-format.yml
- include/core/event_bus.hpp
- src/rendering/gl_resources.hpp
- src/rendering/gl_state_guard.hpp
- src/visualizer/tools/tool_base.hpp
> check clang format in github actions

- include/core/camera.hpp
- include/core/dataset.hpp
- include/core/parameters.hpp
- src/argument_parser.cpp
- src/camera.cpp
- src/trainer.cpp
Saves a render of specified images every N steps in training. I had to do some unpleasant stuff so the cameras were initialized correctly at the start of training but the fix seems to work. I also have an ffmpeg command that converts the images into a video but I am not sure where the best place to display the command is.
> Add timelapse image saving

- src/visualizer/gui/panels/training_panel.cpp
- src/visualizer/gui/ui_widgets.cpp
> expose params

- src/loader/loaders/colmap_loader.cpp
> prioritize colmap .bin over .txt if both exists

- include/core/events.hpp
- src/visualizer/gui/panels/scene_panel.cpp
- src/visualizer/input/input_controller.cpp
- src/visualizer/scene/scene.cpp
- src/visualizer/scene/scene.hpp
- src/visualizer/scene/scene_manager.cpp
https://github.com/user-attachments/assets/ffece35d-72fe-4ad4-a50d-33062b6a13ba
Toggle plys with the T button
> toggle plys

- src/loader/filesystem_utils.hpp
- src/loader/formats/colmap.cpp
- src/loader/loader.cpp
- src/loader/loaders/colmap_loader.cpp
Support structures like this.
.
├── 00000.jpg
├── 00001.jpg
├── 00002.jpg
...
├── 00150.jpg
├── 00151.jpg
├── 00152.jpg
├── Cameras.txt
├── Images.txt
├── Points3D.txt
└── wagon.txt
> support flat rc-like structure

- include/rendering/rendering.hpp
- src/rendering/CMakeLists.txt
- src/rendering/camera_frustum_renderer.cpp
- src/rendering/camera_frustum_renderer.hpp
- src/rendering/rendering_engine_impl.cpp
- src/rendering/rendering_engine_impl.hpp
- src/rendering/resources/shaders/camera_frustum.frag
- src/rendering/resources/shaders/camera_frustum.vert
- src/rendering/shader.hpp
- src/rendering/shader_manager.cpp
- src/rendering/shader_manager.hpp
- src/visualizer/gui/panels/main_panel.cpp
- src/visualizer/rendering/rendering_manager.cpp
- src/visualizer/rendering/rendering_manager.hpp
- src/visualizer/visualizer_impl.cpp
> camera frustum rendering

- include/rendering/rendering.hpp
- src/rendering/camera_frustum_renderer.cpp
- src/rendering/camera_frustum_renderer.hpp
- src/rendering/rendering_engine_impl.cpp
- src/rendering/rendering_engine_impl.hpp
- src/visualizer/input/input_controller.cpp
- src/visualizer/input/input_controller.hpp
- src/visualizer/rendering/rendering_manager.cpp
- src/visualizer/rendering/rendering_manager.hpp
https://github.com/user-attachments/assets/f2243ccd-54df-42e8-a2a3-77bf5531c597
> cam frustum pick and goto works

- CMakeLists.txt
- README.md
- scripts/benchmark_mipnerf360.ps1
- scripts/benchmark_mipnerf360.sh
- scripts/benchmark_mipnerf360_adc.sh
- scripts/benchmark_mipnerf360_mcmc.sh
- scripts/timing_mipnerf360.ps1
- scripts/timing_mipnerf360_default.sh
- scripts/timing_mipnerf360_mcmc.sh
- src/rendering/cuda/CMakeLists.txt
- src/training/CMakeLists.txt
- src/training/metrics/metrics.cpp
- src/visualizer/CMakeLists.txt
> update cmake/scripts/readme for the repo name change

- .github/workflows/ubuntu.yml
- .github/workflows/windows.yml
Hopefully to cut the windows CI runtime by 20 mins
> ci: cache vcpkg binary archives

- README.md
update readme - link to windows docs changed
> Update README.md - link to windows docs changed

- src/rendering/cuda_gl_interop.cpp
What: Add a helper `clear_cuda_error_if_present()` calling `cudaGetLastError()` (guarded by `CUDA_GL_INTEROP_ENABLED`) and invoke it at interop failure points to clear sticky CUDA error states.
Why: Prevent cascading failures where subsequent CUDA/Torch calls observe a stale error after a CUDA-GL interop failure, ensuring a clean fallback to the CPU copy path.
Scope: Only `src/rendering/cuda_gl_interop.cpp` (13 insertions, 1 deletion). Behavior unchanged on successful interop; affects only error-handling paths.
> Interop: clear stale CUDA errors

- src/visualizer/gui/panels/main_panel.cpp
- src/visualizer/gui/panels/training_panel.cpp
- src/visualizer/gui/ui_widgets.cpp
* add gpu usage to training panel
* added label to the "loss" graph
before:
after:
> Add gpu mem usage

- src/visualizer/gui/panels/crop_box_panel.cpp
1. fit crop box text to match app scale resolution,
2. increased box size to 200
> crop box small modifications

- .gitignore
- src/core/argument_parser.cpp
- Updated Helper Message for Command Line Interface.
- Added .vs to .gitignore.
> Updated CLI Helper Message

- docs/docs/faq.md
Well, a contribution's a contribution I guess
> Minor faq.md changes

- include/project/project.hpp
- src/project/project.cpp
- src/visualizer/gui/panels/scene_panel.cpp
- src/visualizer/scene/scene_manager.cpp
enable remove ply from project
* ply is removed from scene
* ply is removed from project
> remove ply from project
